apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    name: result-deployment 
    app: BTQ-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: result-app-pod
      app: BTQ-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: BTQ-voting-app
    spec:
      containers:
      - name: result-app
        image: Mufaddal789/example-voting-app_result:v1
        ports:
          - containerPort: 80