apiVersion: v1
kind: Service
metadata:
  name: voting-app-pod
  labels:
    name: voting-service
    app: BTQ-voting-app
spec:
  selector:
    name: voting-app-pod
    app: BTQ-voting-app
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004