apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    name: worker-deployment 
    app: BTQ-voting-app
spec:
  replicas: 2
  selector:
    matchLabels:
      name: worker-pod
      app: BTQ-voting-app
  template:
    metadata:
      name: worker-pod
      labels:
        name: worker-pod
        app: BTQ-voting-app
    spec:
      containers:
        - name: worker-app
          image: Mufaddal789/example-voting-app_worker:v1